import styled from "@emotion/styled";
import Head from "next/head";
import { inter } from "./_app";

const Button = styled.button`
  background-color: ${(props) => props.theme.colors.primary};
  color: white;
  padding: 0.8rem 1rem;
  border: none;
  cursor: pointer;
  border-radius: 5px;
  font-size: 1rem;
  margin: 0.5rem 0.2rem 0.5rem 0;
  box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);
  font-family: inherit;
  transition: all 0.3s ease;

  &:active {
    transform: scale(0.9);
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatterWorld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className={inter.className}>Hello World! Welcome to Chatter World</h1>
        <div className="card bsh">
          <h2>Post Text</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero sed dicta, ratione soluta qui similique
            debitis, ut sunt voluptate nulla cum aperiam, neque corrupti dolor quod incidunt assumenda aliquam dolore?
          </p>
          <Button className="btn">Click here</Button>
          <button className="btn secondary">Click here</button>
          <button className="btn danger">Click here</button>
          <button className="btn success">Click here</button>
        </div>
      </div>
    </>
  );
}
