import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatterWorld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello World! Welcome to Chatter World</h1>
        <div className="card bsh">
          <h2>Post Text</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero sed dicta, ratione soluta qui similique
            debitis, ut sunt voluptate nulla cum aperiam, neque corrupti dolor quod incidunt assumenda aliquam dolore?
          </p>
          <button className="btn">Click here</button>
          <button className="btn secondary">Click here</button>
          <button className="btn danger">Click here</button>
          <button className="btn success">Click here</button>
        </div>
      </div>
    </>
  );
}
